### ISSUE TITLE
Exception : android.content.IntentSender$SendIntentException

### ISSUE THREAD

**Issue by rikinpatoliya** [SanojPunchihewa/InAppUpdater#10]
android.content.IntentSender$SendIntentException
generated when call more than one time startUpdate() method.

**Comment by SanojPunchihewa** [comment]
@rikinpatoliya thanks for the issue. I'm quite busy these days. If you have time to fix it please submit a Pull Request.

**Comment by SanojPunchihewa** [comment]
Closing with the fix #11
