### ISSUE TITLE
InAppUpdater sees the update, but can't install it

### ISSUE THREAD

**Issue by konstantin-doncov** [SanojPunchihewa/InAppUpdater#14]
**Describe the bug**
I'm trying to use your library, all works fine, but after the update installation is completed and the program restarts, I see the old version.

**To Reproduce**
For testing I created a simple application with `versionCode 3`(before this I posted `versionCode 2` in the internal test track, but I did not see updates in my application with `versionCode 1`) and uploaded it in the Google play in a closed track(alpha version).

Code:

    public class UpdateActivity extends AppCompatActivity {
    
        private UpdateManager mUpdateManager;
    
        static final int REQUEST_CODE = 781;
    
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_update);
    
            TextView txtCurrentVersion = findViewById(R.id.currentVersion);
            TextView txtAvailableVersion = findViewById(R.id.availableVersion);
    
            txtCurrentVersion.setText(String.valueOf(BuildConfig.VERSION_CODE));
    
            // Initialize the Update Manager with the Activity and the Update Mode
            mUpdateManager = UpdateManager.Builder(this);
    
            // Callback from Available version code
            mUpdateManager.getAvailableVersionCode(code -> txtAvailableVersion.setText(String.valueOf(code)));
        }
    
        @Override
        protected void onResume() {
            super.onResume();
            // Continue updates when resumed
            mUpdateManager.continueUpdate();
        }
    
    
        @Override
        public void onActivityResult(int requestCode, int resultCode, Intent data) {
            super.onActivityResult(requestCode, resultCode, data);
            if (requestCode == REQUEST_CODE) {
                if (resultCode == RESULT_OK) {
                    Log.d("MyTag", "Result ok! Result code: " + resultCode);
                }
                else if(resultCode == RESULT_CANCELED){
                    Log.d("MyTag", "Result canceled! Result code: " + resultCode);
    
                }
                else if(resultCode == ActivityResult.RESULT_IN_APP_UPDATE_FAILED){
                    Log.d("MyTag", "In app update failed! Result code: " + resultCode);
    
                }
            }
        }
    
    
        public void tryToUpdate(View view){
            mUpdateManager.mode(UpdateManagerConstant.FLEXIBLE).start();
        }
    
    }

After starting, I see that current version = 2, available version = 3, so the app sees the update. Next I click the `tryToUpdate` button and see the update dialog, click "update", wait, see "An update has just been downloaded", click "restart", see installation activity, after that my application restarts and I see the old version - current version = 2, and this is the problem. Of course, I tried to manually close and open the app but I still see the old version. But if I delete the old version and manually install the new version from Google Play, then all works fine.

So, how can I solve this?

**Expected behavior**
I expect to see current version = 3, available version = 3.

 - OS: Android 8.1.0

**Comment by SanojPunchihewa** [comment]
Are you testing the app(version = 2) in debug mode? If that's the case you need to sign the apk with same key used to build app(version = 3) and build a signed apk. Hope this will solve your issue. If not please let me know.
The reason android OS is not able to install the update as the current app(version = 2) is not signed.

**Comment by konstantin-doncov** [comment]
I tried this, unfortunately this doesn't work.

**Comment by SanojPunchihewa** [comment]
Sorry for being away. I tried the same code you have added above and was not able to reproduce the problem when I'm using signed apks(**Build -> Generate Signed Bundle / APK**). But I was able to experience the [behavior](https://github.com/SanojPunchihewa/InAppUpdater/blob/master/FAQ.md#1-the-app-downloads-the-update-but-it-wont-install-the-update) you have stated when **just running the app via Android Studio using the debug mode** and just building apks(**without signing**)(**Build -> Build Bundle(s) / APK(s)**)

**Comment by konstantin-doncov** [comment]
This is strange, but Google support says this:

> Please note that we only support the update while you have downloaded your app from Google Play at least once before using the account to test in-app updates.
> To solve this issue, please download app with version 1.2 in Google Play Store and upload a new apk with higher version in Alpha track. After it pass the review, you can try the in-app update again.

> Unfortunatly, we are only able to assist the issue if the app is downloaded from Google Play Store instead of installing APK files manually.
> Please note that the error install from other source is out of our scope. As a result, we'll still recommend you to use the In App Updates feature while the app is downloaded from our Google Play Store.

So, I downloaded 1.2 on my phone, upload 1.3 to the Google Play, and now I can update my app. But if I build signed apk with 1.2 version using the same key and download it to my phone, I can't do the same, and this is strange because you can do it. Anyway, I think it's Google's area of ​​responsibility. Thanks!
