### ISSUE TITLE
app not updating after installing from in-app update screen.

### ISSUE THREAD

**Issue by onirban27** [SanojPunchihewa/InAppUpdater#30]
app dialog appears that a new version available then i click on update button and update download starts. when app update download completes a snackbar pop ups and if i click on restart then the in-app update screen appears and starts installing but it doesn't show any updated screen. it just goes away and app restarts but version stays same and when i exit and reopen app it again shows the dialog. this is very confusing.

Samsung a10 , android 9

**Comment by SanojPunchihewa** [comment]
This occurs when the app with lower version code hasn't signed with the same key used in the higher version app. Can you please try this [guide](https://github.com/SanojPunchihewa/InAppUpdater/blob/master/FAQ.md#1-the-app-downloads-the-update-but-it-wont-install-the-update). Hope it will solve the issue, if not please let me know

**Comment by priyashpatil** [comment]
> app dialog appears that a new version available then i click on update button and update download starts. when app update download completes a snackbar pop ups and if i click on restart then the in-app update screen appears and starts installing but it doesn't show any updated screen. it just goes away and app restarts but version stays same and when i exit and reopen app it again shows the dialog. this is very confusing.
> 
> Samsung a10 , android 9

Make sure you install app from play store first then release update. It won't work if app is installed outside of play store.

**Comment by priyashpatil** [comment]
Make sure you install app from play store first then release update. It won't work if app is installed outside of play store.

**Comment by onirban27** [comment]
Thanks @SanojPunchihewa it was happening because it wasn't signed with the same key as play console.
