### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JavaDeveloper08** [SanojPunchihewa/InAppUpdater#37]
Hi, thank you very much for your effort,

I implemented your library but I have a problem.

For example, my local version is 4.5 and version of app in store is 4.6. 

App is updated but local version is not changing, Whenever I opened my app always asks update needed. 

Please help this issue.

**Comment by SanojPunchihewa** [comment]
Can you please check [this](https://github.com/SanojPunchihewa/InAppUpdater/blob/master/FAQ.md#1-the-app-downloads-the-update-but-it-wont-install-the-update)

**Comment by SanojPunchihewa** [comment]
Closing as no response from the author
