### ISSUE TITLE
flexible update not working.

### ISSUE THREAD

**Issue by skpnchl** [SanojPunchihewa/InAppUpdater#50]
lateinit var updateManager: UpdateManager

in onCreate() method: 

updateManager = UpdateManager.Builder(this).mode(UpdateManagerConstant.FLEXIBLE)
updateManager.start()

my app in GooglePlay but still not getting update window. (update not working.)

**Comment by SanojPunchihewa** [comment]
Please make sure you have followed these [Guidelines](https://github.com/SanojPunchihewa/InAppUpdater#exclamation-troubleshoot)
