### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by STPLAmrut** [SanojPunchihewa/InAppUpdater#53]
UpdateManager mUpdateManager;
mUpdateManager = UpdateManager.Builder(this).mode(UpdateManagerConstant.FLEXIBLE);
mUpdateManager.start();

Added in gradle-
implementation 'com.github.SanojPunchihewa:InAppUpdater:1.0.5

Everything is added and fine and as per guideline but not working after update.

**Comment by SanojPunchihewa** [comment]
Please make sure you have followed these [Guidelines](https://github.com/SanojPunchihewa/InAppUpdater#exclamation-troubleshoot)
