### ISSUE TITLE
[BUG] I've got NPE report from firebase

### ISSUE THREAD

**Issue by jc01rho** [SanojPunchihewa/InAppUpdater#62]
**Describe the bug**
i've used this repo 1.0.5-alpha.1, reported NPE from firebase crashlytics.

**To Reproduce**
Sorry, i can't reproduce it.

**Screenshots**
![image](https://user-images.githubusercontent.com/4989674/91783793-32a3a600-ec3c-11ea-8303-53c006c6ec48.png)

**Desktop (please complete the following information):**
 - OS: android 9, galaxyS8

**Additional context**
None

**Comment by SanojPunchihewa** [comment]
Thanks for reporting the issue, will check this and let you know

**Comment by SanojPunchihewa** [comment]
Closing as no response from the author
