### ISSUE TITLE
Subscription pause and resubscribe

### ISSUE THREAD

**Issue by rausNT** [SanojPunchihewa/InAppUpdater#71]
Hi.
I got the following message from Google:
"You must have account hold and restore implemented in your app by November 1, 2020. Subscription pause and resubscribe will also be enabled by default, unless you opt out."
Is this feature planned to be maintained?

**Comment by SanojPunchihewa** [comment]
Hi @rausNT The above message has nothing to do with this library.

> If your Android app sells subscription products, then you will need to make sure these subscription features (account hold, restore, pause, and resubscribe) are supported. If your Android app does not sell subscription products, you will not need to worry about this upcoming change

For more info, please check [https://issuetracker.google.com/issues/170592154](https://issuetracker.google.com/issues/170592154)
