### ISSUE TITLE
Could not find com.github.SanojPunchihewa:InAppUpdater:1.0.3.

### ISSUE THREAD

**Issue by Indark-a-bit** [SanojPunchihewa/InAppUpdater#8]
Any suggestions?

**Comment by SanojPunchihewa** [comment]
Did you add jitpack to your root level Gradle?if not add it and try
```
allprojects {
    repositories {
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by Indark-a-bit** [comment]
OfCourse! It was not able to find this library. Can you check?

**Comment by SanojPunchihewa** [comment]
@Indark-a-bit Looks like there was an issue in the release. Thanks for pointing it out. You can use the new release.
```
implementation 'com.github.SanojPunchihewa:InAppUpdater:1.0.4-alpha.1'
```
